### PR TITLE
Add k6 binary for darwin and linux and make the app use it

### PR DESCRIPTION
**Pull request by oleiade**
This is very experimental ⚠️

If while using this PR the application fails, please let me know 🙏🏻 (#ItWorksOnMyMachine)

This PR adds the k6 binary for macos (M1), and Linux to the application, and makes it use that instead of the path's. Getting this to work was tricky at best, so please le me know if you experience issues 👍🏻

### CODE REVIEW

**Comment by Llandy3d** [comment]
just to keep track of things, this doesn't work on the m1 mac. At least the dashboard url can't be reachable while k6 seems to run 🤔 

We keep this as a problem for later because we would have to make this work on linux/mac/windows.
A more sensible option for the prototype is to just ask the user to have k6 installed

**Comment by allansson** [comment]
> We keep this as a problem for later because we would have to make this work on linux/mac/windows. A more sensible option for the prototype is to just ask the user to have k6 installed

I a real-world app, couldn't we look into compiling k6 as a static library and link that in Rust? 🤔

**Comment by Llandy3d** [comment]
> > We keep this as a problem for later because we would have to make this work on linux/mac/windows. A more sensible option for the prototype is to just ask the user to have k6 installed
> 
> I a real-world app, couldn't we look into compiling k6 as a static library and link that in Rust? 🤔

that's the approach taken by Theo :) 

There are nuances depending on os, for example on macos the bundled k6 binary doesn't seem to be able to open the http server while it should work on linux.
In a real world scenario yes, k6 would be bundled so that the correct version would be in sync with the app

**Comment by Llandy3d** [comment]
Closing this as the binary situation has been solved in #56

**Pull request closed without merging**
